import React, { useState, useEffect } from 'react';
import { CheckCircle2, Circle, Trash2, Plus, Clock, Calendar, Sparkles, Target, Filter, ChevronRight, HelpCircle } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

// SVG Progress Ring component
function ProgressRing({ radius = 36, stroke = 5, progress = 0, color = 'var(--primary)' }) {
  const normalizedRadius = radius - stroke;
  const circumference = 2 * Math.PI * normalizedRadius;
  const offset = circumference - (progress / 100) * circumference;

  return (
    <svg height={radius * 2} width={radius * 2} style={{ transform: 'rotate(-90deg)' }}>
      {/* Track */}
      <circle
        stroke="var(--border-subtle)"
        strokeWidth={stroke}
        fill="transparent"
        r={normalizedRadius}
        cx={radius}
        cy={radius}
      />
      {/* Progress */}
      <circle
        stroke={color}
        strokeWidth={stroke}
        fill="transparent"
        strokeLinecap="round"
        strokeDasharray={circumference}
        strokeDashoffset={offset}
        r={normalizedRadius}
        cx={radius}
        cy={radius}
        style={{ transition: 'stroke-dashoffset 0.6s cubic-bezier(0.16,1,0.3,1)' }}
      />
    </svg>
  );
}

const FILTERS = [
  { id: 'all',    label: 'All Tasks' },
  { id: 'active', label: 'Active' },
  { id: 'done',   label: 'Completed' },
];

export default function GlobalTasks({ onOpenGuide }) {
  const { authFetch } = useAuth();
  const [tasks, setTasks] = useState([]);
  const [newTask, setNewTask] = useState('');
  const [newDeadline, setNewDeadline] = useState('');
  const [filter, setFilter] = useState('all');
  const [adding, setAdding] = useState(false);

  const fetchTasks = async () => {
    try {
      const res = await authFetch('/api/tasks');
      if (res.ok) setTasks(await res.json());
    } catch (err) {
      console.error('Failed to fetch tasks', err);
    }
  };

  useEffect(() => {
    fetchTasks();
    const handleTaskUpdate = () => fetchTasks();
    window.addEventListener('tasks-updated', handleTaskUpdate);
    return () => window.removeEventListener('tasks-updated', handleTaskUpdate);
  }, []);

  const addTask = async () => {
    if (!newTask.trim()) return;
    setAdding(true);
    try {
      const res = await authFetch('/api/tasks', {
        method: 'POST',
        body: JSON.stringify({ description: newTask, deadline: newDeadline || null })
      });
      if (res.ok) {
        setNewTask('');
        setNewDeadline('');
        fetchTasks();
      }
    } catch (err) {
      console.error('Failed to add task', err);
    } finally {
      setAdding(false);
    }
  };

  const toggleTask = async (task) => {
    try {
      const res = await authFetch(`/api/tasks/${task.id}`, {
        method: 'PUT',
        body: JSON.stringify({ done: task.done ? 0 : 1 })
      });
      if (res.ok) fetchTasks();
    } catch (err) {
      console.error('Failed to toggle task', err);
    }
  };

  const deleteTask = async (id) => {
    try {
      const res = await authFetch(`/api/tasks/${id}`, { method: 'DELETE' });
      if (res.ok) fetchTasks();
    } catch (err) {
      console.error('Failed to delete task', err);
    }
  };

  const handleAddToCalendar = (task) => {
    const now = new Date();
    now.setMinutes(now.getMinutes() + 15);
    const start = now.toISOString().replace(/-|:|\.\d\d\d/g, '');
    const later = new Date(now.getTime() + 60 * 60 * 1000);
    const end = later.toISOString().replace(/-|:|\.\d\d\d/g, '');
    const title = encodeURIComponent(task.description);
    const details = encodeURIComponent(task.deadline ? `Deadline: ${task.deadline}` : 'Generated by MeetingMind');
    window.open(`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}&dates=${start}/${end}`, '_blank');
  };

  const totalTasks = tasks.length;
  const doneTasks = tasks.filter(t => t.done).length;
  const activeTasks = totalTasks - doneTasks;
  const progress = totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0;

  const filteredTasks = tasks.filter(t => {
    if (filter === 'active') return !t.done;
    if (filter === 'done') return t.done;
    return true;
  });

  const progressColor = progress === 100 ? '#10b981' : progress >= 50 ? '#14b8a6' : '#f97316';

  return (
    <div style={{ padding: '28px', maxWidth: '860px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '20px' }}>

      {/* ── HEADER: Stats + Progress Ring ── */}
      <div className="glass-panel fade-in-up" style={{ padding: '24px 28px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '24px', flexWrap: 'wrap', background: 'var(--bg-surface)' }}>
        <div style={{ flex: 1 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '6px' }}>
            <div style={{ width: '34px', height: '34px', borderRadius: '10px', background: 'var(--teal-bg)', border: '1px solid var(--teal-border)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Target size={17} color="var(--primary)" />
            </div>
            <h2 style={{ fontSize: '1.3rem', fontWeight: 800, letterSpacing: '-0.02em', color: 'var(--text-main)', margin: 0 }}>
              Action Items
            </h2>
            <span className="badge badge-primary" style={{ fontSize: '0.68rem' }}>
              <Sparkles size={10} /> Global Checklist
            </span>
            <button
              onClick={() => onOpenGuide && onOpenGuide('tasks')}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '5px',
                padding: '3px 10px',
                borderRadius: 'var(--radius-full)',
                border: '1px solid var(--border-medium)',
                background: 'var(--bg-input)',
                color: 'var(--text-muted)',
                fontSize: '0.74rem',
                fontWeight: 600,
                cursor: 'pointer',
                fontFamily: 'inherit',
                transition: 'all 0.15s ease'
              }}
              onMouseEnter={e => {
                e.currentTarget.style.borderColor = 'var(--primary)';
                e.currentTarget.style.color = 'var(--primary)';
              }}
              onMouseLeave={e => {
                e.currentTarget.style.borderColor = 'var(--border-medium)';
                e.currentTarget.style.color = 'var(--text-muted)';
              }}
              title="Learn how Action Items work"
            >
              <HelpCircle size={12} color="var(--primary)" />
              <span>Guide</span>
            </button>
          </div>
          <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)', margin: 0 }}>
            Persistent task list synced across all meeting extractions.
          </p>

          {/* Stat Pills */}
          <div style={{ display: 'flex', gap: '12px', marginTop: '16px', flexWrap: 'wrap' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'var(--bg-input)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-full)', padding: '5px 13px', fontSize: '0.78rem', fontWeight: 700 }}>
              <span style={{ width: '7px', height: '7px', borderRadius: '50%', background: '#f97316', display: 'inline-block' }} />
              <span style={{ color: 'var(--text-main)' }}>{activeTasks}</span>
              <span style={{ color: 'var(--text-dim)' }}>active</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'var(--bg-input)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-full)', padding: '5px 13px', fontSize: '0.78rem', fontWeight: 700 }}>
              <span style={{ width: '7px', height: '7px', borderRadius: '50%', background: '#10b981', display: 'inline-block' }} />
              <span style={{ color: 'var(--text-main)' }}>{doneTasks}</span>
              <span style={{ color: 'var(--text-dim)' }}>completed</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'var(--bg-input)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-full)', padding: '5px 13px', fontSize: '0.78rem', fontWeight: 700 }}>
              <span style={{ color: 'var(--text-main)' }}>{totalTasks}</span>
              <span style={{ color: 'var(--text-dim)' }}>total</span>
            </div>
          </div>
        </div>

        {/* Progress Ring */}
        {totalTasks > 0 && (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '6px', flexShrink: 0 }}>
            <div style={{ position: 'relative', width: '80px', height: '80px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <ProgressRing radius={40} stroke={5} progress={progress} color={progressColor} />
              <div style={{ position: 'absolute', textAlign: 'center' }}>
                <div style={{ fontSize: '1.2rem', fontWeight: 900, color: progressColor, lineHeight: 1 }}>{progress}%</div>
              </div>
            </div>
            <span style={{ fontSize: '0.72rem', fontWeight: 600, color: 'var(--text-dim)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              Progress
            </span>
          </div>
        )}
      </div>

      {/* ── ADD TASK PANEL ── */}
      <div className="glass-panel fade-in-up delay-100" style={{ padding: '18px 20px', display: 'flex', flexDirection: 'column', gap: '12px' }}>
        <div style={{ fontSize: '0.72rem', fontWeight: 700, color: 'var(--text-dim)', textTransform: 'uppercase', letterSpacing: '0.05em', display: 'flex', alignItems: 'center', gap: '6px' }}>
          <Plus size={12} /> New Task
        </div>
        <input
          className="input-field"
          placeholder="What needs to be done? Press Enter to add quickly..."
          value={newTask}
          onChange={e => setNewTask(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && addTask()}
          style={{ fontSize: '0.92rem', padding: '11px 14px' }}
          id="new-task-input"
        />
        <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
          <div style={{ position: 'relative', flex: 1 }}>
            <Clock size={14} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-dim)', pointerEvents: 'none' }} />
            <input
              className="input-field"
              placeholder="Deadline (optional, e.g. Friday 5PM, Oct 10)"
              value={newDeadline}
              onChange={e => setNewDeadline(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && addTask()}
              style={{ fontSize: '0.84rem', paddingLeft: '34px' }}
            />
          </div>
          <button
            onClick={addTask}
            disabled={!newTask.trim() || adding}
            className="btn btn-primary"
            style={{ padding: '9px 22px', flexShrink: 0 }}
            id="add-task-btn"
          >
            <Plus size={15} />
            <span>{adding ? 'Adding...' : 'Add'}</span>
          </button>
        </div>
      </div>

      {/* ── FILTER TABS ── */}
      {tasks.length > 0 && (
        <div className="fade-in delay-150" style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          <Filter size={13} color="var(--text-dim)" />
          <div style={{ display: 'flex', gap: '4px', background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)', padding: '4px' }}>
            {FILTERS.map(f => (
              <button
                key={f.id}
                onClick={() => setFilter(f.id)}
                style={{
                  padding: '5px 14px',
                  borderRadius: '7px',
                  border: 'none',
                  cursor: 'pointer',
                  fontSize: '0.78rem',
                  fontWeight: 600,
                  fontFamily: 'inherit',
                  background: filter === f.id ? 'var(--primary-gradient)' : 'transparent',
                  color: filter === f.id ? '#ffffff' : 'var(--text-muted)',
                  transition: 'all 0.15s ease',
                  boxShadow: filter === f.id ? '0 2px 8px rgba(20,184,166,0.3)' : 'none',
                }}
              >
                {f.label}
                {f.id !== 'all' && (
                  <span style={{ marginLeft: '6px', fontSize: '0.7rem', fontWeight: 700, opacity: 0.8 }}>
                    ({f.id === 'active' ? activeTasks : doneTasks})
                  </span>
                )}
              </button>
            ))}
          </div>
          <span style={{ marginLeft: 'auto', fontSize: '0.76rem', color: 'var(--text-dim)', fontWeight: 600 }}>
            {filteredTasks.length} task{filteredTasks.length !== 1 ? 's' : ''}
          </span>
        </div>
      )}

      {/* ── TASK LIST ── */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
        {tasks.length === 0 && (
          <div className="glass-panel fade-in-up delay-200" style={{ padding: '60px 20px', textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '14px' }}>
            <div style={{ width: '60px', height: '60px', borderRadius: '16px', background: 'var(--teal-bg)', border: '1px solid var(--teal-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '4px' }}>
              <CheckCircle2 size={28} color="var(--primary)" />
            </div>
            <div style={{ fontWeight: 700, fontSize: '1rem', color: 'var(--text-main)' }}>No action items yet</div>
            <div style={{ fontSize: '0.84rem', color: 'var(--text-muted)', maxWidth: '280px', lineHeight: 1.5 }}>
              Action items auto-populate from meeting extractions, or add your own above.
            </div>
          </div>
        )}

        {filteredTasks.length === 0 && tasks.length > 0 && (
          <div style={{ padding: '30px', textAlign: 'center', color: 'var(--text-dim)', fontSize: '0.88rem' }}>
            No {filter === 'done' ? 'completed' : 'active'} tasks.
          </div>
        )}

        {filteredTasks.map((task, i) => (
          <div
            key={task.id}
            className={`glass-panel task-card slide-right${task.done ? ' done' : ''}`}
            style={{
              padding: '16px 18px',
              display: 'flex',
              gap: '14px',
              alignItems: 'flex-start',
              animationDelay: `${i * 40}ms`,
              borderLeft: task.done ? '3px solid var(--emerald)' : '3px solid var(--border-subtle)',
              transition: 'all 0.2s ease',
            }}
          >
            {/* Checkbox */}
            <button
              onClick={() => toggleTask(task)}
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '2px', marginTop: '1px', flexShrink: 0, transition: 'transform 0.15s ease' }}
              title={task.done ? 'Mark as active' : 'Mark as done'}
              onMouseEnter={e => { e.currentTarget.style.transform = 'scale(1.2)'; }}
              onMouseLeave={e => { e.currentTarget.style.transform = 'scale(1)'; }}
            >
              {task.done
                ? <CheckCircle2 size={21} color="#10b981" />
                : <Circle size={21} color="var(--text-dim)" />
              }
            </button>

            {/* Content */}
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{
                fontSize: '0.92rem',
                color: task.done ? 'var(--text-dim)' : 'var(--text-main)',
                textDecoration: task.done ? 'line-through' : 'none',
                wordBreak: 'break-word',
                lineHeight: 1.5,
                fontWeight: task.done ? 400 : 500,
              }}>
                {task.description}
              </div>
              {task.deadline && (
                <div style={{ fontSize: '0.76rem', marginTop: '7px', display: 'flex', alignItems: 'center', gap: '5px', color: task.done ? 'var(--text-dim)' : '#f59e0b', fontWeight: 600 }}>
                  <Clock size={11} />
                  <span>Due: {task.deadline}</span>
                </div>
              )}
            </div>

            {/* Actions */}
            <div style={{ display: 'flex', gap: '4px', flexShrink: 0 }}>
              <button
                onClick={() => handleAddToCalendar(task)}
                data-tooltip="Add to Calendar"
                style={{
                  background: 'none', border: '1px solid var(--border-subtle)', cursor: 'pointer',
                  padding: '6px 8px', color: '#3b82f6', borderRadius: 'var(--radius-sm)',
                  transition: 'all 0.15s ease', display: 'flex', alignItems: 'center'
                }}
                onMouseEnter={e => { e.currentTarget.style.background = 'rgba(59,130,246,0.1)'; e.currentTarget.style.borderColor = 'rgba(59,130,246,0.35)'; }}
                onMouseLeave={e => { e.currentTarget.style.background = 'none'; e.currentTarget.style.borderColor = 'var(--border-subtle)'; }}
                title="Add to Google Calendar"
              >
                <Calendar size={14} />
              </button>
              <button
                onClick={() => deleteTask(task.id)}
                data-tooltip="Delete task"
                style={{
                  background: 'none', border: '1px solid var(--border-subtle)', cursor: 'pointer',
                  padding: '6px 8px', color: 'var(--text-dim)', borderRadius: 'var(--radius-sm)',
                  transition: 'all 0.15s ease', display: 'flex', alignItems: 'center'
                }}
                onMouseEnter={e => { e.currentTarget.style.background = 'var(--rose-bg)'; e.currentTarget.style.color = 'var(--rose)'; e.currentTarget.style.borderColor = 'var(--rose-border)'; }}
                onMouseLeave={e => { e.currentTarget.style.background = 'none'; e.currentTarget.style.color = 'var(--text-dim)'; e.currentTarget.style.borderColor = 'var(--border-subtle)'; }}
                title="Delete task"
              >
                <Trash2 size={14} />
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* ── FOOTER summary ── */}
      {tasks.length > 0 && (
        <div className="fade-in" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 4px', fontSize: '0.76rem', color: 'var(--text-dim)', borderTop: '1px solid var(--border-subtle)' }}>
          <span>{doneTasks} of {totalTasks} tasks completed</span>
          {doneTasks > 0 && (
            <button
              onClick={async () => {
                for (const t of tasks.filter(t => t.done)) await deleteTask(t.id);
              }}
              style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--rose)', fontSize: '0.76rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '4px' }}
              onMouseEnter={e => e.currentTarget.style.opacity = '0.7'}
              onMouseLeave={e => e.currentTarget.style.opacity = '1'}
            >
              <Trash2 size={12} /> Clear Completed
            </button>
          )}
        </div>
      )}
    </div>
  );
}
